server:
  port: 8080

spring:
  application:
    name: tradingserver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB


  datasource:
    name: tradingdb
    url: ${MYSQL_URL}?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  flyway:
    locations: classpath:db/migration

  sql:
    init:
      mode: always


  #jpa settings
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    health:
      mail:
        enabled: false


#JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expirations: ${JWT_EXPIRATION}
  reset-password-xpiration: ${JWT_RESET_PASSWORD_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  serverAccessExpiration: ${JWT_SERVER_ACCESS_EXPIRATION}


# AWS Credentials
cloud:
  aws:
    region:
      static: ${AWS_REGION}



logging:
  level:
    org.hibernate: warn
    org.hibernate.orm.connections.pooling: warn
    org.hibernate.orm.deprecation: error
    org.springframework.orm.jpa: warn